# Generated by Django 5.2.17 on 2026-09-18 05:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('scope', models.CharField(blank=True, max_length=100)),
                ('busy_until', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('preview', models.JSONField()),
                ('snapshot', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('state', models.CharField(default='pending', max_length=12)),
                ('result', models.JSONField(null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agentconversation')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agentconversation')),
            ],
        ),
    ]
