# Generated by Django 5.2.17 on 2026-09-18 07:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agentconversation_agentproposal_agentturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_embedding', models.TextField(editable=False)),
                ('model_version', models.CharField(editable=False, max_length=64)),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('consent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
