# Generated by Django 5.2.17 on 2026-09-21 08:34

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_taskparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='letter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Xat sanasi'),
        ),
        migrations.AddField(
            model_name='task',
            name='letter_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Xat raqami'),
        ),
        migrations.AddField(
            model_name='task',
            name='letter_sender',
            field=models.CharField(blank=True, max_length=180, verbose_name='Xat kimdan kelgan'),
        ),
        migrations.AddField(
            model_name='taskparticipant',
            name='kind',
            field=models.CharField(choices=[('executor', 'Qo‘shimcha ijrochi'), ('controller', 'Nazoratchi')], default='executor', max_length=12),
        ),
        migrations.AlterField(
            model_name='taskparticipant',
            name='part',
            field=models.CharField(blank=True, max_length=240, verbose_name='Ijro qismi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chair', 'Boshqaruv raisi'), ('head', 'Bo‘lim boshlig‘i'), ('office', 'Devonxona mudiri'), ('secretary', 'Kotiba'), ('employee', 'Xodim')], default='employee', max_length=12, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=300, upload_to=core.models.attachment_path, verbose_name='Fayl')),
                ('name', models.CharField(max_length=180)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
