# Generated by Django 5.2.17 on 2026-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Telegram orqali kirish uchun: 998901234567', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
