# Generated by Django 5.2.17 on 2026-09-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_telegram_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.task'),
        ),
    ]
