# Generated by Django 5.2.17 on 2026-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_follows_its_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervised',
            field=models.ManyToManyField(blank=True, related_name='deputies', to='core.department', verbose_name='Nazorat qiladigan bo‘linmalar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chair', 'Boshqaruv raisi'), ('deputy', 'Rais o‘rinbosari'), ('head', 'Bo‘lim boshlig‘i'), ('office', 'Devonxona mudiri'), ('secretary', 'Kotiba'), ('employee', 'Xodim')], default='employee', max_length=12, verbose_name='Rol'),
        ),
    ]
